name: "Unit & Smoke Tests - mamba"
on:
  pull_request:
    paths:
      - wandb/test/**
      
  workflow_dispatch:

defaults:
  run:
    shell: bash -el {0}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Copy Repository Contents
        uses: actions/checkout@main   
   
      - name: Install Conda environment with Micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: wandb/test/conda-enviroment.yaml
          environment-name: conda-env-autextification
          cache-env: true
          cache-downloads: true
          
      - run: |
          micromamba activate conda-env-autextification
          pip install -U pytest
          pip install -U pyyaml
          pytest wandb/test/
